# Lecture 2

Help for functions or commands is written with a `?...`.

In [1]:
?+

search: + .+



```
+(x, y...)
```

Addition operator. `x+y+z+...` calls this function with all arguments, i.e. `+(x, y, z, ...)`.

```
dt::Date + t::Time -> DateTime
```

The addition of a `Date` with a `Time` produces a `DateTime`. The hour, minute, second, and millisecond parts of the `Time` are used along with the year, month, and day of the `Date` to create the new `DateTime`. Non-zero microseconds or nanoseconds in the `Time` type will result in an `InexactError` being thrown.


In [2]:
?*

search: * .*



```
*(s::AbstractString, t::AbstractString)
```

Concatenate strings. The `*` operator is an alias to this function.

# Example

```jldoctest
julia> "Hello " * "world"
"Hello world"
```

```
*(x, y...)
```

Multiplication operator. `x*y*z*...` calls this function with all arguments, i.e. `*(x, y, z, ...)`.

```
*(A::AbstractMatrix, B::AbstractMatrix)
```

Matrix multiplication.

# Example

```jldoctest
julia> [1 1; 0 1] * [1 0; 1 1]
2×2 Array{Int64,2}:
 2  1
 1  1
```


Julia methods have _multiple dispatch_ which means that the methods depend on the name and the input.  That is, the method will behave differently under different input parameters.  For example, `methods(+)` shows a different perspective on how `+` acts.

In [3]:
methods(+)

# 180 methods for generic function "+":
+(x::Bool, z::Complex{Bool}) in Base at complex.jl:232
+(x::Bool, y::Bool) in Base at bool.jl:89
+(x::Bool) in Base at bool.jl:86
+(x::Bool, y::T) where T<:AbstractFloat in Base at bool.jl:96
+(x::Bool, z::Complex) in Base at complex.jl:239
+(a::Float16, b::Float16) in Base at float.jl:372
+(x::Float32, y::Float32) in Base at float.jl:374
+(x::Float64, y::Float64) in Base at float.jl:375
+(z::Complex{Bool}, x::Bool) in Base at complex.jl:233
+(z::Complex{Bool}, x::Real) in Base at complex.jl:247
+(x::Char, y::Integer) in Base at char.jl:40
+(c::BigInt, x::BigFloat) in Base.MPFR at mpfr.jl:312
+(a::BigInt, b::BigInt, c::BigInt, d::BigInt, e::BigInt) in Base.GMP at gmp.jl:334
+(a::BigInt, b::BigInt, c::BigInt, d::BigInt) in Base.GMP at gmp.jl:327
+(a::BigInt, b::BigInt, c::BigInt) in Base.GMP at gmp.jl:321
+(x::BigInt, y::BigInt) in Base.GMP at gmp.jl:289
+(x::BigInt, c::Union{UInt16, UInt32, UInt64, UInt8}) in Base.GMP at gmp.jl:346
+(x::BigInt, c::Union{Int16, Int32, Int64, Int8}) in Base.GMP at gmp.jl:362
+(a::BigFloat, b::BigFloat, c::BigFloat, d::BigFloat, e::BigFloat) in Base.MPFR at mpfr.jl:460
+(a::BigFloat, b::BigFloat, c::BigFloat, d::BigFloat) in Base.MPFR at mpfr.jl:453
+(a::BigFloat, b::BigFloat, c::BigFloat) in Base.MPFR at mpfr.jl:447
+(x::BigFloat, c::BigInt) in Base.MPFR at mpfr.jl:308
+(x::BigFloat, y::BigFloat) in Base.MPFR at mpfr.jl:277
+(x::BigFloat, c::Union{UInt16, UInt32, UInt64, UInt8}) in Base.MPFR at mpfr.jl:284
+(x::BigFloat, c::Union{Int16, Int32, Int64, Int8}) in Base.MPFR at mpfr.jl:292
+(x::BigFloat, c::Union{Float16, Float32, Float64}) in Base.MPFR at mpfr.jl:300
+(B::BitArray{2}, J::UniformScaling) in Base.LinAlg at linalg/uniformscaling.jl:59
+(a::Base.Pkg.Resolve.VersionWeights.VWPreBuildItem, b::Base.Pkg.Resolve.VersionWeights.VWPreBuildItem) in Base.Pkg.Resolve.VersionWeights at pkg/resolve/versionweight.jl:87
+(a::Base.Pkg.Resolve.VersionWeights.VWPreBuild, b::Base.Pkg.Resolve.VersionWeights.VWPreBuild) in Base.Pkg.Resolve.VersionWeights at pkg/resolve/versionweight.jl:135
+(a::Base.Pkg.Resolve.VersionWeights.VersionWeight, b::Base.Pkg.Resolve.VersionWeights.VersionWeight) in Base.Pkg.Resolve.VersionWeights at pkg/resolve/versionweight.jl:197
+(a::Base.Pkg.Resolve.MaxSum.FieldValues.FieldValue, b::Base.Pkg.Resolve.MaxSum.FieldValues.FieldValue) in Base.Pkg.Resolve.MaxSum.FieldValues at pkg/resolve/fieldvalue.jl:44
+(x::Base.Dates.CompoundPeriod, y::Base.Dates.CompoundPeriod) in Base.Dates at dates/periods.jl:349
+(x::Base.Dates.CompoundPeriod, y::Base.Dates.Period) in Base.Dates at dates/periods.jl:347
+(x::Base.Dates.CompoundPeriod, y::Base.Dates.TimeType) in Base.Dates at dates/periods.jl:387
+(x::Date, y::Base.Dates.Day) in Base.Dates at dates/arithmetic.jl:77
+(x::Date, y::Base.Dates.Week) in Base.Dates at dates/arithmetic.jl:75
+(dt::Date, z::Base.Dates.Month) in Base.Dates at dates/arithmetic.jl:58
+(dt::Date, y::Base.Dates.Year) in Base.Dates at dates/arithmetic.jl:32
+(dt::Date, t::Base.Dates.Time) in Base.Dates at dates/arithmetic.jl:20
+(t::Base.Dates.Time, dt::Date) in Base.Dates at dates/arithmetic.jl:24
+(x::Base.Dates.Time, y::Base.Dates.TimePeriod) in Base.Dates at dates/arithmetic.jl:81
+(dt::DateTime, z::Base.Dates.Month) in Base.Dates at dates/arithmetic.jl:52
+(dt::DateTime, y::Base.Dates.Year) in Base.Dates at dates/arithmetic.jl:28
+(x::DateTime, y::Base.Dates.Period) in Base.Dates at dates/arithmetic.jl:79
+(y::AbstractFloat, x::Bool) in Base at bool.jl:98
+(x::T, y::T) where T<:Union{Int128, Int16, Int32, Int64, Int8, UInt128, UInt16, UInt32, UInt64, UInt8} in Base at int.jl:32
+(x::Integer, y::Ptr) in Base at pointer.jl:128
+(z::Complex, w::Complex) in Base at complex.jl:221
+(z::Complex, x::Bool) in Base at complex.jl:240
+(x::Real, z::Complex{Bool}) in Base at complex.jl:246
+(x::Real, z::Complex) in Base at complex.jl:258
+(z::Complex, x::Real) in Base at complex.jl:259
+(x::Rational, y::Rational) in Base at rational.jl:245

So in the above we see that dates can be added.  See the following example.

In [4]:
Dates.today()

2017-11-06

In [5]:
dd = Dates.today()+Dates.Day(135)

2018-03-21

In [6]:
typeof(dd)

Date

### Adding tridiagonal matrices

In [7]:
methods(Tridiagonal)

# 6 methods for generic function "(::Type)":
(::Type{Tridiagonal})(dl::Array{T,1}, d::Array{T,1}, du::Array{T,1}) where T in Base.LinAlg at linalg/tridiag.jl:436
(::Type{Tridiagonal})(dl::Array{T,1}, d::Array{T,1}, du::Array{T,1}, du2::Array{T,1}) where T in Base.LinAlg at linalg/tridiag.jl:389
(::Type{Tridiagonal})(M::Bidiagonal{T}) where T in Base.LinAlg at linalg/bidiag.jl:205
(::Type{Tridiagonal})(dl::AbstractArray{Tl,1}, d::AbstractArray{Td,1}, du::AbstractArray{Tu,1}) where {Tl, Td, Tu} in Base.LinAlg at linalg/tridiag.jl:445
(::Type{Tridiagonal})(A::AbstractArray{T,2} where T) in Base.LinAlg at linalg/tridiag.jl:474
(::Type{T})(arg) where T in Base at sysimg.jl:77

In [8]:
T1 = Tridiagonal(rand(6), rand(7), rand(6))

7×7 Tridiagonal{Float64}:
 0.0930483  0.665637    ⋅          ⋅          ⋅          ⋅         ⋅      
 0.0894266  0.0705192  0.0107994   ⋅          ⋅          ⋅         ⋅      
  ⋅         0.161493   0.589888   0.998918    ⋅          ⋅         ⋅      
  ⋅          ⋅         0.908057   0.418693   0.0142942   ⋅         ⋅      
  ⋅          ⋅          ⋅         0.0937068  0.171499   0.442291   ⋅      
  ⋅          ⋅          ⋅          ⋅         0.790658   0.224327  0.975084
  ⋅          ⋅          ⋅          ⋅          ⋅         0.501454  0.820116

In [9]:
full(T1)

7×7 Array{Float64,2}:
 0.0930483  0.665637   0.0        0.0        0.0        0.0       0.0     
 0.0894266  0.0705192  0.0107994  0.0        0.0        0.0       0.0     
 0.0        0.161493   0.589888   0.998918   0.0        0.0       0.0     
 0.0        0.0        0.908057   0.418693   0.0142942  0.0       0.0     
 0.0        0.0        0.0        0.0937068  0.171499   0.442291  0.0     
 0.0        0.0        0.0        0.0        0.790658   0.224327  0.975084
 0.0        0.0        0.0        0.0        0.0        0.501454  0.820116

In [10]:
T2 = Tridiagonal(rand(-5:5,6), rand(7), rand(-9:0,6))

7×7 Tridiagonal{Float64}:
  0.219195  -2.0         ⋅          ⋅          ⋅          ⋅          ⋅     
 -1.0        0.641626  -7.0         ⋅          ⋅          ⋅          ⋅     
   ⋅        -1.0        0.362087  -8.0         ⋅          ⋅          ⋅     
   ⋅          ⋅         1.0        0.160808  -5.0         ⋅          ⋅     
   ⋅          ⋅          ⋅         2.0        0.181028  -3.0         ⋅     
   ⋅          ⋅          ⋅          ⋅        -5.0        0.392962  -1.0    
   ⋅          ⋅          ⋅          ⋅          ⋅         3.0        0.28115

In [11]:
T3 = T1 + T2

7×7 Tridiagonal{Float64}:
  0.312243  -1.33436     ⋅          ⋅          ⋅          ⋅          ⋅       
 -0.910573   0.712145  -6.9892      ⋅          ⋅          ⋅          ⋅       
   ⋅        -0.838507   0.951976  -7.00108     ⋅          ⋅          ⋅       
   ⋅          ⋅         1.90806    0.579501  -4.98571     ⋅          ⋅       
   ⋅          ⋅          ⋅         2.09371    0.352528  -2.55771     ⋅       
   ⋅          ⋅          ⋅          ⋅        -4.20934    0.617289  -0.0249155
   ⋅          ⋅          ⋅          ⋅          ⋅         3.50145    1.10127  

In [12]:
@which T1 + T2

+(A::Tridiagonal, B::Tridiagonal) in Base.LinAlg at linalg/tridiag.jl:624

In [13]:
println(T3.dl, T3.d, T3.du) # get the diagonals

[-0.910573, -0.838507, 1.90806, 2.09371, -4.20934, 3.50145][0.312243, 0.712145, 0.951976, 0.579501, 0.352528, 0.617289, 1.10127][-1.33436, -6.9892, -7.00108, -4.98571, -2.55771, -0.0249155]


In [14]:
T4 = Tridiagonal([1,2,3], [2.0,3.0,pi,4.0],rand(3)+im*rand(3))

4×4 Tridiagonal{Complex{Float64}}:
 2.0+0.0im  0.632029+0.823354im           ⋅                    ⋅         
 1.0+0.0im       3.0+0.0im       0.191763+0.149114im           ⋅         
     ⋅           2.0+0.0im        3.14159+0.0im       0.285965+0.122921im
     ⋅               ⋅                3.0+0.0im            4.0+0.0im     

In [15]:
# can use size() and full()
size(T4)

(4, 4)

In [16]:
T4 = full(T4)

4×4 Array{Complex{Float64},2}:
 2.0+0.0im  0.632029+0.823354im       0.0+0.0im            0.0+0.0im     
 1.0+0.0im       3.0+0.0im       0.191763+0.149114im       0.0+0.0im     
 0.0+0.0im       2.0+0.0im        3.14159+0.0im       0.285965+0.122921im
 0.0+0.0im       0.0+0.0im            3.0+0.0im            4.0+0.0im     

Exploiting structured matrices can lead to more efficient programs as we can store only a collection of nonzero entries.

In [17]:
sizeof(T1)

32

In [18]:
T1_full = full(T1)

7×7 Array{Float64,2}:
 0.0930483  0.665637   0.0        0.0        0.0        0.0       0.0     
 0.0894266  0.0705192  0.0107994  0.0        0.0        0.0       0.0     
 0.0        0.161493   0.589888   0.998918   0.0        0.0       0.0     
 0.0        0.0        0.908057   0.418693   0.0142942  0.0       0.0     
 0.0        0.0        0.0        0.0937068  0.171499   0.442291  0.0     
 0.0        0.0        0.0        0.0        0.790658   0.224327  0.975084
 0.0        0.0        0.0        0.0        0.0        0.501454  0.820116

In [19]:
sizeof(T1_full)

392

The tridiagonal method is immutable so we can change individual parts but not the whole thing.

In [20]:
@show T5 = Tridiagonal([1,2,3], [2,3,4,5], [-1,1,2])
T5.d[2] = 123
@show T5
T5.dl = [-1, -1, 1]

T5 = Tridiagonal([1, 2, 3], [2, 3, 4, 5], [-1, 1, 2]) = [2 -1 0 0; 1 3 1 0; 0 2 4 2; 0 0 3 5]
T5 = [2 -1 0 0; 1 123 1 0; 0 2 4 2; 0 0 3 5]


LoadError: type Tridiagonal is immutable

There is no general method for the multiplication of tridiagonal matrices so they are first converted to full matrices.

In [21]:
T1*T2

7×7 Array{Float64,2}:
 -0.645241    0.240993  -4.65946    …   0.0        0.0         0.0      
 -0.0509174  -0.144406  -0.489724       0.0        0.0         0.0      
 -0.161493   -0.48627    0.0820586     -4.99459    0.0         0.0      
  0.0        -0.908057   0.747489      -2.09088   -0.0428826   0.0      
  0.0         0.0        0.0937068     -2.64894   -0.340694   -0.442291 
  0.0         0.0        0.0        …  -0.978502   0.64143     0.0498185
  0.0         0.0        0.0           -2.50727    2.6574     -0.270878 

In [22]:
@which T1*T2

*(A::Union{Bidiagonal, SymTridiagonal, Tridiagonal}, B::Union{Bidiagonal, SymTridiagonal, Tridiagonal}) in Base.LinAlg at linalg/bidiag.jl:499

### The ` \dot ` operator

In [23]:
x = rand(1:5,5); y  = rand(-5:0,5); a = x⋅y
z = rand(5); b = x⋅z; c = z⋅x
w = rand(5) + im*rand(5); d = x⋅w; ee = z⋅w; f = w⋅z
@show x, y, z, w
@show a, b, c, d, e, f

(x, y, z, w) = ([2, 4, 3, 4, 3], [0, -2, 0, -3, -4], [0.789798, 0.348268, 0.539671, 0.445101, 0.469635], Complex{Float64}[0.260263+0.147267im, 0.263341+0.708907im, 0.647701+0.0373171im, 0.0996191+0.981324im, 0.367495+0.0738093im])
(a, b, c, d, e, f) = (-32, 7.7809882876164185, 7.7809882876164185, 5.01795546046626 + 7.3888377550983435im, e = 2.7182818284590..., 0.863742958437647 - 0.85479179160189im)


(-32, 7.7809882876164185, 7.7809882876164185, 5.01795546046626 + 7.3888377550983435im, e = 2.7182818284590..., 0.863742958437647 - 0.85479179160189im)

the command `whos()` shows the content for a package or a module.

In [24]:
whos(Dates)

               @dateformat_str      0 bytes  Base.Dates.#@dateformat_str
                           Apr      8 bytes  Int64
                         April      8 bytes  Int64
                           Aug      8 bytes  Int64
                        August      8 bytes  Int64
                          Date    112 bytes  DataType
                    DateFormat     80 bytes  UnionAll
                    DatePeriod     92 bytes  DataType
                      DateTime    112 bytes  DataType
                         Dates  20915 KB     Module
                      Datetime      0 bytes  Base.Dates.#Datetime
                           Day    112 bytes  DataType
                           Dec      8 bytes  Int64
                      December      8 bytes  Int64
                           Feb      8 bytes  Int64
                      February      8 bytes  Int64
                           Fri      8 bytes  Int64
                        Friday      8 bytes  Int64
                          Hou

## Packages

In [25]:
# can check the status of a package.
?Pkg.status()

LoadError: UndefVarError: ? not defined

In [26]:
Pkg.status()

6 required packages:
 - Graphs                        0.8.0
 - IJulia                        1.6.2
 - IJuliaPortrayals              0.0.4
 - Interact                      0.6.2
 - Primes                        0.2.0
 - Winston                       0.13.1
22 additional packages:
 - BinDeps                       0.7.0
 - Cairo                         0.3.1
 - ColorTypes                    0.6.6
 - Colors                        0.8.2
 - Compat                        0.34.0
 - Conda                         0.7.0
 - DataStructures                0.7.2
 - FixedPointNumbers             0.4.3
 - Graphics                      0.2.0
 - Homebrew                      0.6.0
 - IniFile                       0.3.1
 - JSON                          0.15.2
 - MbedTLS                       0.5.1
 - NaNMath                       0.2.6
 - Reactive                      0.6.0
 - Reexport                      0.0.3
 - SHA                           0.5.2
 - SpecialFunctions              0.3.4
 - StatsBase    

In [27]:
?Pkg.add

```
add(pkg, vers...)
```

Add a requirement entry for `pkg` to `Pkg.dir("REQUIRE")` and call `Pkg.resolve()`. If `vers` are given, they must be `VersionNumber` objects and they specify acceptable version intervals for `pkg`.


In [28]:
using Graphs

In [29]:
whos(Graphs)

             @graph_implements      0 bytes  Graphs.#@graph_implements
               @graph_requires      0 bytes  Graphs.#@graph_requires
       AbstractDijkstraVisitor     92 bytes  DataType
 AbstractEdgePropertyInspector     40 bytes  UnionAll
                 AbstractGraph     80 bytes  UnionAll
          AbstractGraphVisitor     92 bytes  DataType
            AbstractMASVisitor     92 bytes  DataType
           AbstractPrimVisitor     92 bytes  DataType
                 AdjacencyList     40 bytes  UnionAll
                 AttributeDict    212 bytes  DataType
AttributeEdgePropertyInspector     40 bytes  UnionAll
             BellmanFordStates     80 bytes  UnionAll
                  BreadthFirst     92 bytes  DataType
 ConstantEdgePropertyInspector     40 bytes  UnionAll
                    DepthFirst     92 bytes  DataType
                DijkstraStates    160 bytes  UnionAll
                          Edge     40 bytes  UnionAll
                      EdgeList     80 bytes  Union

 strongly_connected_components      0 bytes  Graphs.#strongly_connected_compone…
                        target      0 bytes  Graphs.#target
            test_cyclic_by_dfs      0 bytes  Graphs.#test_cyclic_by_dfs
                        to_dot      0 bytes  Graphs.#to_dot
       topological_sort_by_dfs      0 bytes  Graphs.#topological_sort_by_dfs
                traverse_graph      0 bytes  Graphs.#traverse_graph
        traverse_graph_withlog      0 bytes  Graphs.#traverse_graph_withlog
                  vertex_index      0 bytes  Graphs.#vertex_index
                   vertex_type      0 bytes  Graphs.#vertex_type
                      vertices      0 bytes  Graphs.#vertices
              visited_vertices      0 bytes  Graphs.#visited_vertices
          watts_strogatz_graph      0 bytes  Graphs.#watts_strogatz_graph
                 weight_matrix      0 bytes  Graphs.#weight_matrix
          weight_matrix_sparse      0 bytes  Graphs.#weight_matrix_sparse


### Example
We construct the seven bridges of Konigseberg, plot it, and then compute the number of different walks which can cross 3 bridges on the north side and the central island.


In [30]:
g = simple_graph(4, is_directed=false)

Undirected Graph (4 vertices, 0 edges)

In [31]:
add_edge!(g,1,2)
add_edge!(g,1,2)
add_edge!(g,1,3)
add_edge!(g,1,3)
add_edge!(g,1,4)
add_edge!(g,2,4)
add_edge!(g,3,4)
g

Undirected Graph (4 vertices, 7 edges)

In [32]:
using IJuliaPortrayals

LoadError: LoadError: UndefVarError: writemime not defined
while loading /Users/cdickens/.julia/v0.6/IJuliaPortrayals/src/IJuliaPortrayals.jl, in expression starting on line 254

In [33]:
GraphViz(to_dot(g),"neato", "svg")

LoadError: UndefVarError: GraphViz not defined

In [34]:
a = adjacency_matrix(g)

4×4 Array{Bool,2}:
 false   true   true   true
  true  false  false   true
  true  false  false   true
  true   true   true  false

In [35]:
edges(g)

7-element Array{Graphs.Edge{Int64},1}:
 edge [1]: 1 -- 2
 edge [2]: 1 -- 2
 edge [3]: 1 -- 3
 edge [4]: 1 -- 3
 edge [5]: 1 -- 4
 edge [6]: 2 -- 4
 edge [7]: 3 -- 4

In [37]:
weights = [2, 2, 2, 2, 1, 1, 1]
a = weight_matrix(g,weights)

4×4 Array{Int64,2}:
 0  2  2  1
 2  0  0  1
 2  0  0  1
 1  1  1  0

In [38]:
num_walks = (a^3)[1,2]

22